// DO NOT EDIT. generated by github.com/tinywasm/ormc

package sitemanager

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type Site struct {
	Id string
	Slug string
	Name string
	Domain string
	DomainExpiresAt int64
	Plan string
	Theme string
	Status int64
	Dirty bool
	PublishedAt int64
	PublishedRef string
}

func (m *Site) ModelName() string { return "site" }

func (m *Site) Schema() []model.Field { return SiteModel.Fields }

func (m *Site) Pointers() []any { return []any{&m.Id, &m.Slug, &m.Name, &m.Domain, &m.DomainExpiresAt, &m.Plan, &m.Theme, &m.Status, &m.Dirty, &m.PublishedAt, &m.PublishedRef} }

func (m *Site) IsNil() bool { return m == nil }

func (m *Site) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("slug", m.Slug)
	w.String("name", m.Name)
	w.String("domain", m.Domain)
	w.Int("domain_expires_at", m.DomainExpiresAt)
	w.String("plan", m.Plan)
	w.String("theme", m.Theme)
	w.Int("status", m.Status)
	w.Bool("dirty", m.Dirty)
	w.Int("published_at", m.PublishedAt)
	w.String("published_ref", m.PublishedRef)
}

func (m *Site) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("slug"); ok { m.Slug = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("domain"); ok { m.Domain = v }
	if v, ok := r.Int("domain_expires_at"); ok { m.DomainExpiresAt = v }
	if v, ok := r.String("plan"); ok { m.Plan = v }
	if v, ok := r.String("theme"); ok { m.Theme = v }
	if v, ok := r.Int("status"); ok { m.Status = v }
	if v, ok := r.Bool("dirty"); ok { m.Dirty = v }
	if v, ok := r.Int("published_at"); ok { m.PublishedAt = v }
	if v, ok := r.String("published_ref"); ok { m.PublishedRef = v }
}

type SiteList []*Site

func (s *SiteList) Schema() []model.Field { return nil }
func (s *SiteList) Pointers() []any     { return nil }
func (s *SiteList) Len() int             { return len(*s) }
func (s *SiteList) At(i int) model.Fielder { return (*s)[i] }
func (s *SiteList) Append() model.Fielder  { v := &Site{}; *s = append(*s, v); return v }
func (s *SiteList) IsNil() bool          { return s == nil }
func (s *SiteList) EncodeFields(_ model.FieldWriter) {}
func (s *SiteList) DecodeFields(_ model.FieldReader) {}

func (m *Site) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Site_ = struct {
	Id string
	Slug string
	Name string
	Domain string
	DomainExpiresAt string
	Plan string
	Theme string
	Status string
	Dirty string
	PublishedAt string
	PublishedRef string
}{
	Id: "id",
	Slug: "slug",
	Name: "name",
	Domain: "domain",
	DomainExpiresAt: "domain_expires_at",
	Plan: "plan",
	Theme: "theme",
	Status: "status",
	Dirty: "dirty",
	PublishedAt: "published_at",
	PublishedRef: "published_ref",
}

func ReadOneSite(qb *orm.QB, model *Site) (*Site, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllSite(qb *orm.QB) (SiteList, error) {
	var results SiteList
	err := qb.ReadAll(
		func() model.Model { return &Site{} },
		func(m model.Model) { results = append(results, m.(*Site)) },
	)
	return results, err
}

type SiteMember struct {
	Id string
	SiteId string
	UserId string
	Role int64
}

func (m *SiteMember) ModelName() string { return "site_member" }

func (m *SiteMember) Schema() []model.Field { return SiteMemberModel.Fields }

func (m *SiteMember) Pointers() []any { return []any{&m.Id, &m.SiteId, &m.UserId, &m.Role} }

func (m *SiteMember) IsNil() bool { return m == nil }

func (m *SiteMember) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("site_id", m.SiteId)
	w.String("user_id", m.UserId)
	w.Int("role", m.Role)
}

func (m *SiteMember) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("site_id"); ok { m.SiteId = v }
	if v, ok := r.String("user_id"); ok { m.UserId = v }
	if v, ok := r.Int("role"); ok { m.Role = v }
}

type SiteMemberList []*SiteMember

func (s *SiteMemberList) Schema() []model.Field { return nil }
func (s *SiteMemberList) Pointers() []any     { return nil }
func (s *SiteMemberList) Len() int             { return len(*s) }
func (s *SiteMemberList) At(i int) model.Fielder { return (*s)[i] }
func (s *SiteMemberList) Append() model.Fielder  { v := &SiteMember{}; *s = append(*s, v); return v }
func (s *SiteMemberList) IsNil() bool          { return s == nil }
func (s *SiteMemberList) EncodeFields(_ model.FieldWriter) {}
func (s *SiteMemberList) DecodeFields(_ model.FieldReader) {}

func (m *SiteMember) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var SiteMember_ = struct {
	Id string
	SiteId string
	UserId string
	Role string
}{
	Id: "id",
	SiteId: "site_id",
	UserId: "user_id",
	Role: "role",
}

func ReadOneSiteMember(qb *orm.QB, model *SiteMember) (*SiteMember, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllSiteMember(qb *orm.QB) (SiteMemberList, error) {
	var results SiteMemberList
	err := qb.ReadAll(
		func() model.Model { return &SiteMember{} },
		func(m model.Model) { results = append(results, m.(*SiteMember)) },
	)
	return results, err
}

func (m *SiteMember) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: SiteMemberModel.Fields[1], Ref: "site", RefColumn: "id", OnDelete: ""},
	}
}

type Plan struct {
	Name string
	MaxPages int64
	MaxImages int64
	CustomDomain bool
}

func (m *Plan) ModelName() string { return "plan" }

func (m *Plan) Schema() []model.Field { return PlanModel.Fields }

func (m *Plan) Pointers() []any { return []any{&m.Name, &m.MaxPages, &m.MaxImages, &m.CustomDomain} }

func (m *Plan) IsNil() bool { return m == nil }

func (m *Plan) EncodeFields(w model.FieldWriter) {
	w.String("name", m.Name)
	w.Int("max_pages", m.MaxPages)
	w.Int("max_images", m.MaxImages)
	w.Bool("custom_domain", m.CustomDomain)
}

func (m *Plan) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.Int("max_pages"); ok { m.MaxPages = v }
	if v, ok := r.Int("max_images"); ok { m.MaxImages = v }
	if v, ok := r.Bool("custom_domain"); ok { m.CustomDomain = v }
}

type PlanList []*Plan

func (s *PlanList) Schema() []model.Field { return nil }
func (s *PlanList) Pointers() []any     { return nil }
func (s *PlanList) Len() int             { return len(*s) }
func (s *PlanList) At(i int) model.Fielder { return (*s)[i] }
func (s *PlanList) Append() model.Fielder  { v := &Plan{}; *s = append(*s, v); return v }
func (s *PlanList) IsNil() bool          { return s == nil }
func (s *PlanList) EncodeFields(_ model.FieldWriter) {}
func (s *PlanList) DecodeFields(_ model.FieldReader) {}

func (m *Plan) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Plan_ = struct {
	Name string
	MaxPages string
	MaxImages string
	CustomDomain string
}{
	Name: "name",
	MaxPages: "max_pages",
	MaxImages: "max_images",
	CustomDomain: "custom_domain",
}

func ReadOnePlan(qb *orm.QB, model *Plan) (*Plan, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPlan(qb *orm.QB) (PlanList, error) {
	var results PlanList
	err := qb.ReadAll(
		func() model.Model { return &Plan{} },
		func(m model.Model) { results = append(results, m.(*Plan)) },
	)
	return results, err
}

type AccessRequest struct {
	Id string
	Email string
	Name string
	Message string
	CreatedAt int64
	Status int64
}

func (m *AccessRequest) ModelName() string { return "access_request" }

func (m *AccessRequest) Schema() []model.Field { return AccessRequestModel.Fields }

func (m *AccessRequest) Pointers() []any { return []any{&m.Id, &m.Email, &m.Name, &m.Message, &m.CreatedAt, &m.Status} }

func (m *AccessRequest) IsNil() bool { return m == nil }

func (m *AccessRequest) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("email", m.Email)
	w.String("name", m.Name)
	w.String("message", m.Message)
	w.Int("created_at", m.CreatedAt)
	w.Int("status", m.Status)
}

func (m *AccessRequest) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("message"); ok { m.Message = v }
	if v, ok := r.Int("created_at"); ok { m.CreatedAt = v }
	if v, ok := r.Int("status"); ok { m.Status = v }
}

type AccessRequestList []*AccessRequest

func (s *AccessRequestList) Schema() []model.Field { return nil }
func (s *AccessRequestList) Pointers() []any     { return nil }
func (s *AccessRequestList) Len() int             { return len(*s) }
func (s *AccessRequestList) At(i int) model.Fielder { return (*s)[i] }
func (s *AccessRequestList) Append() model.Fielder  { v := &AccessRequest{}; *s = append(*s, v); return v }
func (s *AccessRequestList) IsNil() bool          { return s == nil }
func (s *AccessRequestList) EncodeFields(_ model.FieldWriter) {}
func (s *AccessRequestList) DecodeFields(_ model.FieldReader) {}

func (m *AccessRequest) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var AccessRequest_ = struct {
	Id string
	Email string
	Name string
	Message string
	CreatedAt string
	Status string
}{
	Id: "id",
	Email: "email",
	Name: "name",
	Message: "message",
	CreatedAt: "created_at",
	Status: "status",
}

func ReadOneAccessRequest(qb *orm.QB, model *AccessRequest) (*AccessRequest, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllAccessRequest(qb *orm.QB) (AccessRequestList, error) {
	var results AccessRequestList
	err := qb.ReadAll(
		func() model.Model { return &AccessRequest{} },
		func(m model.Model) { results = append(results, m.(*AccessRequest)) },
	)
	return results, err
}
